---
- name: Patch Windows systems
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - Updates
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: no
      register: update_result
