---
- name: Patch Windows systems
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - Updates
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: no
      register: update_result

    - name: Reboot if required
      ansible.windows.win_reboot:
        reboot_timeout: 3600
      when: update_result.reboot_required
